version: '3'
volumes:
  sah-database-data:

services:
  mariadb:
    image: mariadb:10.4.12
    volumes:
      - sah-database-data:/var/lib/mysql
      - ./01-db-nkom.sh:/docker-entrypoint-initdb.d/01-db-nkom.sh:ro
    environment:
      - MYSQL_DATABASE=sah
      - MYSQL_USER=sah
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_TWO=nkom
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
  elastisearch:
    image: elasticsearch:7.13.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.13.2
    container_name: kibana_alb
    #    restart: unless-stopped
    #    depends_on:
    #      - elasticsearch
#    networks:
#      - elastic
    ports:
      - "127.0.0.1:5601:5601"
    logging:
      driver: json-file
    environment:
      ELASTICSEARCH_HOSTS: http://134.0.61.186:9200/
